name: ci

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: "📦 build and push"
    runs-on: ubuntu-latest
    steps:
      - name: "🔄 checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: "⏬ get faas-cli"
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: "⚙ set up qemu"
        uses: docker/setup-qemu-action@v2
      
      - name: "⚙ set up docker buildx"
        uses: docker/setup-buildx-action@v2

      - name: "👤 parse repo owner"
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: "🤝 login to container registry"
        uses: docker/login-action@v2
        with:
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: "🔨 build and publish"
        env:
          TAG: ${{ github.sha }}
          OWNER: ${{ env.REPO_OWNER }}
        run: |
          faas template store pull golang-middleware
          faas-cli publish \
            --extra-tag ${{ env.TAG }} \
            --extra-tag latest-dev \
            --platforms linux/amd64,linux/arm/v7,linux/arm64

  deploy:
    runs-on: ubuntu-latest
    name: "🚀 deploy to dev"
    needs: build
    env:
      OPENFAAS_URL: "${{ vars.FAASD_HOST }}:${{ vars.FAASD_PORT }}"
      OPENFAAS_PASSWORD: ${{ secrets.FAASD_PASSWORD }}
    steps:
      - name: "🔄 checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: "⏬ get faas-cli"
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: "👤 parse repo owner"
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: "🔌 ingressing tailscale network"
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.54.0

      - name: "🏓 testing connection"
        shell: bash
        run: |
          count=10
          while ! ping -c 1 ${{ vars.FAASD_HOST }}; do
            echo "waiting..." ;
            sleep 1;
            let count=count-1
          done

      - name: "🤝 login to openfaas"
        run: |
          echo ${{secrets.FAASD_PASSWORD}} |
          faas-cli login --gateway ${{env.OPENFAAS_URL}} --password-stdin

      - name: "🚀 deploy"
        env:
          TAG: ${{ github.sha }}
          OWNER: ${{ env.REPO_OWNER }}
        run: |
          faas template store pull golang-middleware
          faas-cli deploy --gateway ${{env.OPENFAAS_URL}} --namespace develop
