name: cd

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "🚀 deploy to prod"
    env:
      OPENFAAS_URL: "${{ vars.FAASD_HOST }}:${{ vars.FAASD_PORT }}"
      OPENFAAS_PASSWORD: ${{ secrets.FAASD_PASSWORD }}
    steps:
      - name: "🔄 checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: "⏬ get faas-cli"
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: "👤 parse repo owner"
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: "🤝 login to container registry"
        uses: docker/login-action@v2
        with:
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: "🏷 tag as latest"
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          docker pull ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest-dev
          docker tag ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest-dev ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
          docker tag ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest-dev ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ github.sha}}
          docker push --all-tags ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}

      - name: "🔌 ingressing tailscale network"
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.54.0

      - name: "🏓 testing connection"
        shell: bash
        run: |
          count=10
          while ! ping -c 1 ${{ vars.FAASD_HOST }}; do
            echo "waiting..." ;
            sleep 1;
            let count=count-1
          done

      - name: "🤝 login to openfaas"
        run: |
          echo ${{secrets.FAASD_PASSWORD}} |
          faas-cli login --gateway ${{env.OPENFAAS_URL}} --password-stdin

      - name: "🚀 deploy"
        env:
          TAG: latest
          OWNER: ${{ env.REPO_OWNER }}
        run: |
          faas template store pull golang-middleware
          faas-cli deploy --gateway ${{env.OPENFAAS_URL}}
